### ISSUE TITLE
The table-processor processes pipes (|) that are outside tables

### ISSUE THREAD

**Issue by brigitte-youitv** [jeffreytse/jekyll-spaceship#10]
I found a tiny bug - if I have a pipe `|` somewhere in my text that's not in a table, the text is still seemingly processed by the table-processor. 

For example, compare this output without jekyll-spaceship:

![image](https://user-images.githubusercontent.com/51926419/84571983-0a0abf00-ad65-11ea-8d93-bf261dabbae3.png)

to this output with jekyll-spaceship:

![image](https://user-images.githubusercontent.com/51926419/84572011-39213080-ad65-11ea-83a6-1e3959e700e7.png)

The problem seems to happen regardless of whether or not I surround my `|` with liquid raw tags. Here is the code I'm using. Note that without jekyll-spaceship I don't need the raw tags, but they don't hinder either. With jekyll-spaceship, I get the same results (depicted above) regardless of whether or not I specify raw.

```markdown
Tips:
* Use pipes {% raw %}(`|`){% endraw %} to delineate columns, and dashes to delineate the header row from the rest of the table.
* Spacing doesn't matter to the markdown processor, any extra white space is removed, but it can really help with readability.
The two markdown examples below both create this table.
```

**Comment by jeffreytse** [comment]
Hi @brigitte-youitv 

According to your description, now the problem is addressed and it's a code block processing issue.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @brigitte-youitv

🎉 The latest gem version [v0.6.3](https://rubygems.org/gems/jekyll-spaceship/versions/0.6.3) has been released.

Thanks and regards

**Comment by brigitte-youitv** [comment]
Ahhh! Thank you so much. You work fast! I'll upgrade and it it a try when I'm back at my computer.

**Comment by brigitte-youitv** [comment]
Tested and it works! Fantastic again. Thank you.
