### ISSUE TITLE
Error with permalink file extension

### ISSUE THREAD

**Issue by sekisushai** [jeffreytse/jekyll-spaceship#18]
Hello,
Thank you for the great plugin !

I've noticed that Jekyll builds no longer works when I use permalinks in the YAML front matter with filetype extension other than `.htm` or `.html`.

For example, if I do:

```
---
permalink: /test.php
----
```

I get the following error:

```
" Error: undefined method `css?' for #<Jekyll::Spaceship::TableProcessor:0x000056253cdc1150>"
```

jekyll (4.1.1)
jekyll-spaceship (0.8.4)

**Comment by jeffreytse** [comment]
Hi @sekisushai 

The issue has been addressed and settled. And thanks for your good issue.

Thanks with regards.

**Comment by jeffreytse** [comment]
Hi @sekisushai 

🎉 The latest gem version [v0.8.5](https://rubygems.org/gems/jekyll-spaceship/versions/0.8.5) has been released.

Thanks with regards.
