### ISSUE TITLE
Error:  undefined method `match?' for "tableprocessor":String

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-spaceship#2]
When using ruby 2.3.8 environment, get the following error:

```
$ bundle exec jekyll build

Configuration file: /home/travis/build/jekyll/jekyll-blog/_config.yml
  Jekyll Spaceship: Jekyll-Spaceship 0.2.1
  Jekyll Spaceship: A Jekyll plugin to provide powerful supports.
  Jekyll Spaceship: https://github.com/jeffreytse/jekyll-spaceship
jekyll 3.8.5 | Error:  undefined method `match?' for "tableprocessor":String
Did you mean?  match

The command "bundle exec jekyll build" exited with 1.
```

**Comment by jeffreytse** [comment]
Since the ruby version in this build environment is an old version,
`String#match?` and `Regexp#match?` are `Ruby 2.4` new methods.

This new syntax is **not only an alias**. It's faster than other methods mainly because it doesn't update the `$~` global object. According to this benchmark, it runs up to three times faster than other methods.

**Comment by justinkelly** [comment]
thanks!!!
