### ISSUE TITLE
Bug: Tables row can have links or images, but not both

### ISSUE THREAD

**Issue by brigitte-youitv** [jeffreytse/jekyll-spaceship#20]
I noticed that when I try to add a link to the same table row as an image, that both disappear.

For example, consider this simple table:

```markdown
[cell-image]: https://jekyllrb.com/img/octojekyll.png "An exemplary image"

| Heading                           | Column 1      | Column 2                           |
|-----------------------------------|---------------|------------------------------------|
| Row 1                             | Apple         | Orange                             |
| Row 2 (merged)                    | Blueberry     | Strawberry                         |
| ^^                                | Plum          | Raspberry ![example][cell-image]   |
```

![image](https://user-images.githubusercontent.com/51926419/88593952-56b50b80-d02e-11ea-93d5-a11078a6207b.png)
(Screen capture trimmed so this post isn't super long).

The above displays as expected. And if I modify the last line to *remove* the image and *add* a link to `Plum` like this:

```markdown
| ^^                                | [Plum](https://example.com) | Raspberry                          |
```

I see the link, no problem.
![image](https://user-images.githubusercontent.com/51926419/88593933-4c930d00-d02e-11ea-8fed-8701444aa166.png)

But when I add both the link to `Plum` and the image beside `Raspberry`, neither appear:

```markdown
| ^^                                | [Plum](https://example.com) | Raspberry ![example][cell-image]   |
```

![image](https://user-images.githubusercontent.com/51926419/88593907-42710e80-d02e-11ea-9e7e-519ce16b8986.png)

I made a little project to show you what I mean (attached [zip_bug_both_images_and_links_spaceship.zip](https://github.com/jeffreytse/jekyll-spaceship/files/4984527/zip_bug_both_images_and_links_spaceship.zip)). My screen captures above are from this zipped up project. The changes are all on the main page.

**Comment by jeffreytse** [comment]
Hi @brigitte-youitv 

Thanks for your details about this issue, and now this issue was addressed and settled down.

Thanks with regards.

**Comment by brigitte-youitv** [comment]
Thank you! Updated the bundle and the issue is resolved!
