### ISSUE TITLE
Using jekyll-spaceship kills Liquid

### ISSUE THREAD

**Issue by xjossy** [jeffreytse/jekyll-spaceship#21]
I can't use many characters in Liquid epressions, for example, I'm trying
`{% assign x = 100 %}
{% assign x = x | divided_by 3 %}`

And I got
`Liquid Warning: Liquid syntax error (line 13): Unexpected character \ in "{{x | divided\_by 3 }}" in test.md`

The same situation with `"`: `{% assign t = "a,c,b" | split "," %}` gives 
`Liquid Warning: Liquid syntax error (line 15): Unexpected character \ in "{{\"a,c,b\" | split \",\" }}" in test.md`

**Comment by jeffreytse** [comment]
Hi @xjossy 

Could you provide the environment details such as what jekyll-spaceship version that you are using?

Thanks with regards

**Comment by jeffreytse** [comment]
Hi @xjossy  

🎉 The latest gem version [v0.9.0](https://rubygems.org/gems/jekyll-spaceship/versions/0.8.5) has been released.
Welcome to update to latest version and this issue has been fixed. 

Thanks with regards.

**Comment by xjossy** [comment]
You're amazing, thank you much!
