### ISSUE TITLE
TableProcessor not escaping special chars within code tags

### ISSUE THREAD

**Issue by zedzedzed** [jeffreytse/jekyll-spaceship#27]
Hello

Just wanted to report an issue with the TableProcessor not automatically escaping special characters like angled brackets when within a table cell. By default, Kramdown should be escaping these specials chars as per [1].

Example markdown:

```
Not in table: `<Mail Gateway>`

In table:

Decision Point | Design Decision
--- | ---
Authoritative DNS MX Record | `<Mail Gateway>`
```

Output:

![Screen Shot 2020-10-07 at 3 40 06 pm](https://user-images.githubusercontent.com/4811527/95288289-abd58f00-08b3-11eb-8614-2be9d28f07b6.png)

Thanks
Michael

[1] https://kramdown.gettalong.org/syntax.html#automatic-and-manual-escaping

**Comment by jeffreytse** [comment]
Hi @zedzedzed 

__Thanks for your good issue and help__, now this bug has been fixed. And welcome to __start this repository__ for more future updates. Also, 🎉 the latest gem version [v0.9.3](https://rubygems.org/gems/jekyll-spaceship/versions/0.9.3) has been released.

Thanks and regards

**Comment by zedzedzed** [comment]
Thanks for the amazingly quick turnaround @jeffreytse. The latest version has worked for < and >.
