### ISSUE TITLE
Can't use brackets in table cells

### ISSUE THREAD

**Issue by harper357** [jeffreytse/jekyll-spaceship#32]
I am trying to put a footnote in a table cell, but it doesn't seem to be working with Jekyll Spaceship. 

Example: 
Input:
```
| Header|
|--|
|Words[^1]|

[^1]: Footnote
```
Output without Jekyll Spaceship::
![table](https://user-images.githubusercontent.com/3394695/98294632-1cc89f00-1f65-11eb-9742-c7268c41787b.png)

Output with Jekyll Spaceship::
![table1](https://user-images.githubusercontent.com/3394695/98294797-64e7c180-1f65-11eb-9d4e-b7ce94bfaca0.png)

**Comment by jeffreytse** [comment]
Hi @harper357 

Thanks for your good issue and this issue has been settled now. 🎉 The latest gem version [v0.9.5](https://rubygems.org/gems/jekyll-spaceship/versions/0.9.5) has been released.

Thanks and regards
