### ISSUE TITLE
MathJax processor ignores files with only `$$` (display notation) and text when optimization is enabled

### ISSUE THREAD

**Issue by woodenbell** [jeffreytse/jekyll-spaceship#36]
As the title says, when running the server with the latest version of the plugin (`0.9.6`)  with default configs (`optimize` has `enable: true` for `mathjax`), the MathJax processor is only called on files which have either only mathjax display notation (text between pairs of `$$`) and **no text** or have the inline notation (pairs of `$`).

When using `$$` and regular text or without `$` in that same post, nothing happens.

Below are some screenshots of examples. Setting `enable: false` in the `optimize` config for MathJax seems to solve the issue.

The repository is available [here](https://github.com/woodenbell/jekyll-mathjax-test). 

![Screenshot_2020-12-04 Testing math](https://user-images.githubusercontent.com/30009487/101232317-cba8e980-368f-11eb-87d0-524a8553355c.png)
![Screenshot_2020-12-04 Using only the display notation (no text) works ](https://user-images.githubusercontent.com/30009487/101232319-ce0b4380-368f-11eb-9bb3-031f47d51a92.png)
![Screenshot_2020-12-04 Testing math 2](https://user-images.githubusercontent.com/30009487/101232321-cf3c7080-368f-11eb-8173-5d24efdbd589.png)

**Comment by jeffreytse** [comment]
Hi @woodenbell 

Thanks for your issue firstly. And currently the issue has been addressed.

The minimal test project Gemfile as below:

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.1.1"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "jekyll-spaceship", "0.9.6"

```

The issue could be summarized as below:

1. The post content has only `$$..$$` mathjax expression and no any other content (**Normal**):

```markdown
$$ 2 - 1 = 1 $$
```

```markdown
$$ 2 - 1 = 1 $$

$$ 2 - 1 = 1 $$
```

2. The post content has only `$$..$$` mathjax expression and any other content (**Abnormal**):

```markdown
$$ 2 - 1 = 1 $$

Here is pure text.
```

```markdown
$$ 2 - 1 = 1 $$

<!-- Here is pure text. -->
```

```markdown
$$ 2 - 1 = 1 $$

$$ 3 - 1 = 2 $$

<!-- Here is pure text. -->
```

3.  The post content has only one `$$..$$` and any other patterns (`$..$`, `\\\[...\\\]`, etc.) of mathjax expressions (**Normal**):

```markdown
\\\( 2 - 1 = 1 \\\)

$$ 2 - 1 = 1 $$
```

```markdown
\\\[2 - 1 = 1\\\]

$$ 2 - 1 = 1 $$
```

```markdown
\\\[2 - 1 = 1\\\]

$$ 2 - 1 = 1 $$

Here is pure text.
```

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @woodenbell 

Now the issue has been fixed, and could you update it for your test?
For using gem directly from git repositories. In your Gemfile:

```ruby
# To install a gem from its github repository
gem "jekyll-spaceship", git: "https://github.com/jeffreytse/jekyll-spaceship.git"
```

Thanks and regards

**Comment by woodenbell** [comment]
Hi @jeffreytse
The issue seems to be fixed. Thanks a lot!
![Screenshot_2020-12-05 Testing math](https://user-images.githubusercontent.com/30009487/101268792-47fe0400-3746-11eb-8863-b1524e300349.png)
![Screenshot_2020-12-05 Testing math 2(1)](https://user-images.githubusercontent.com/30009487/101268794-48969a80-3746-11eb-85d4-d2953a124bac.png)
