### ISSUE TITLE
Does it support githubpages?

### ISSUE THREAD

**Issue by tonycheng1995** [jeffreytse/jekyll-spaceship#37]
jekyll-spaceship is effective locally, but it does not work on githubpage. Does it support githubpages?

**Comment by jeffreytse** [comment]
Hi @tonycheng1995 

Sure, this plugin supports Github Pages. [See here, **Additions for Unlimited GitHub Pages**](https://github.com/jeffreytse/jekyll-spaceship#installation)

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @tonycheng1995 

For your convenience, I really suggest you to use this [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) for Github Page.

Thanks and regards

**Comment by tonycheng1995** [comment]
Thanks for your help
