### ISSUE TITLE
emoji processor touches code block strings

### ISSUE THREAD

**Issue by honggaruy** [jeffreytse/jekyll-spaceship#38]
Hi, 
I recently changed the emoji plugin from `jemoji` to `jekyll-spaceship`.

When i was using `jemoji` , it didn't touch the `emoji string (\:+1\:)` in the code block.
```
* I give this plugin two :+1:!
```
This action was what I expected.

But , `jekyll-spaceship` touches the `emoji string` in the code block too ! 
* I give this plugin two :+1:!

The code block string displayed just the same way as above.

Is this a bug ?  Did I miss any configuration setting ?

**Comment by jeffreytse** [comment]
Hi @honggaruy 

Thanks for you reporting and this is a bug actually. Now this issue has been addressed, any update I will update here.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @honggaruy 

:tada: Thanks for your reporting and this issue hans been addressed and settled down.

Thanks and regards.

**Comment by ancailliau** [comment]
It still replaces in single quote code, for example `inet:email:message:to` results in inet:email:message:to

**Comment by jeffreytse** [comment]
@ancailliau Thanks for your issue, now this issue has been settled down, please try with the latest version. : )
