### ISSUE TITLE
Link within angle brackets was corrupted by table rowspan `^^`

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/jekyll-spaceship#47]
Added two urls within angle brackets to make them as links. It works fine at a normal single cell. While it cannot be turned successfully for a url after the `^^` symbol. Here is the test case:

```
| **Windows Application**                                                   ||
| -------------------- | --------------------------------------------------- |
| Application / Softs  | Download links / Webpages                           |
| jekyll-spaceship     | <https://github.com/jeffreytse/jekyll-spaceship>    |
| ^^                   | ^^ <https://github.com/jeffreytse/jekyll-spaceship> |
```

The second url can not be turned into a hyperlink.

![image](https://user-images.githubusercontent.com/24582280/112405941-3751b800-8d4e-11eb-9219-2e19d5446e99.png)

**Comment by longavailable** [comment]
Thank you for your quick response. Works perfectly!
