### ISSUE TITLE
Weird inline Mathjax processing

### ISSUE THREAD

**Issue by honggaruy** [jeffreytse/jekyll-spaceship#50]
Hi, I am not familiar with Mathjax syntax.
But i think this is weird.

```markdown
* A safe integer is an integer that
  * can be exactly represented as an IEEE-754 double precision number, and
  * whose IEEE-75 representation cannot be the result of rounding any other integer to fit the IEEE-754 representation
* For example, $ 2 ^ {53} - 1 $ is a safe integer,
```
![image](https://user-images.githubusercontent.com/24635919/113305632-34525b00-933e-11eb-8beb-50343021fd7f.png)

The above case has no problem where the `Mathjax` line is the last *li* node.
But if I add one more *li* node , it rendered like this; The Mathjax part is not processed.

```markdown
* A safe integer is an integer that
  * can be exactly represented as an IEEE-754 double precision number, and
  * whose IEEE-75 representation cannot be the result of rounding any other integer to fit the IEEE-754 representation
* For example, $ 2 ^ {53} - 1 $ is a safe integer,
  * it can be exactly represented 
```
![image](https://user-images.githubusercontent.com/24635919/113312084-e5f48a80-9344-11eb-8dda-f319b0cf77f4.png)

I want to show one more case.
If I add few more lines and I ended it with `Mathjax` line like this, it shows no problem again.
```markdown
* A safe integer is an integer that
  * can be exactly represented as an IEEE-754 double precision number, and
  * whose IEEE-75 representation cannot be the result of rounding any other integer to fit the IEEE-754 representation
* For example, $ 2 ^ {53} - 1 $ is a safe integer,
  * it can be exactly represented 
  * no other integer rounds to it under any IEEE-754 rounding mode.
* In contrast, $ 2 ^ {53} $ is not a safe integer.
```
![image](https://user-images.githubusercontent.com/24635919/113313628-636cca80-9346-11eb-8649-dda10f26bdd1.png)

But if i add *strong* tag to the `not` word in the last line, the `Mathjax` processor not working again as follows.
```markdown
* A safe integer is an integer that
  * can be exactly represented as an IEEE-754 double precision number, and
  * whose IEEE-75 representation cannot be the result of rounding any other integer to fit the IEEE-754 representation
* For example, $ 2 ^ {53} - 1 $ is a safe integer,
  * it can be exactly represented 
  * no other integer rounds to it under any IEEE-754 rounding mode.
* In contrast, $ 2 ^ {53} $ is **not** a safe integer.
```
![image](https://user-images.githubusercontent.com/24635919/113314213-0887a300-9347-11eb-9157-15aeb5f2d50d.png)

Can you tell me what is the problem ?

**Comment by jeffreytse** [comment]
Hi @honggaruy 

Thank you for the reporting, I will do some further investigation.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @honggaruy 

This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by honggaruy** [comment]
After update, the problem solved !!
