### ISSUE TITLE
Some image links were hijacked to dailymotion

### ISSUE THREAD

**Issue by longavailable** [jeffreytse/jekyll-spaceship#51]
I used a same template to generate image galleries in my site pages. 
Most  works fine. While I found out [MediaProcessor] of [jekyll-spaceship] was invoked accidently and the image links were hijacked to dailymotion. 

![image](https://user-images.githubusercontent.com/24582280/113370684-16651480-9397-11eb-8f3b-d319274f290d.png)

I can not find out the bug point. So I post the pages and their sources built in my site here.

The page built correctly:  <https://longlovemyu.tk/vod-golden-age/>
and its source: <https://raw.githubusercontent.com/longavailable/longavailable.github.io/master/myCollections/_separate-pages/view-of-delft-01-golden-age.md>

The page was wrongly built: <https://longlovemyu.tk/vod-dl/>
and its source: <https://raw.githubusercontent.com/longavailable/longavailable.github.io/master/myCollections/_separate-pages/view-of-delft-04-daily-life.md>

I think it was caused by [jekyll-spaceship]. Because I saw the following logs when I checked locally. Only one of the webpages used a template invoked [MediaProcessor] unexpectedly.

![image](https://user-images.githubusercontent.com/24582280/113370413-6099c600-9396-11eb-9a22-7ed418f952ef.png)

The invoked `includes` is located at <https://raw.githubusercontent.com/longavailable/longavailable.github.io/master/_includes/image-gallery.html> .

`lightbox.js`: 
<https://raw.githubusercontent.com/longavailable/longavailable.github.io/master/js/lightbox.js>.

[MediaProcessor]: https://github.com/jeffreytse/jekyll-spaceship#5-media-usage
[jekyll-spaceship]: https://github.com/jeffreytse/jekyll-spaceship

**Comment by jeffreytse** [comment]
Hi @longavailable 

Thank you for the reporting, I will do some further investigation.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @longavailable 

This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by longavailable** [comment]
Well done. It works fine right now.
