### ISSUE TITLE
Customize `autoplay` attribute in `video` tag ?

### ISSUE THREAD

**Issue by honggaruy** [jeffreytse/jekyll-spaceship#53]
For the media processor, it looks like the `autoplay` attribute is added with the default configuration. (general video usage)
But, I don't want `autoplay` sometimes.

According to the answers of [this quesition](
https://stackoverflow.com/q/19664622/9457247) , the presence of `autoplay` attribute is a shorthand for true.

How can i customize the `autoplay` attribute in video tag ?

**Comment by jeffreytse** [comment]
Hi @honggaruy , 

Could you provide me your code? Actually, the `media-processor` will not set `autoplay` attribute automatically.

Thanks and regards

**Comment by honggaruy** [comment]
Here is my code.

in Markdown
```markdown
![ellystand](https://ksr-video.imgix.net/projects/2693324/video-741087-h264_high.mp4)
```

in Html , I copied this from Chrome Debug Tool
```html
<p>
  <iframe id="media-video-741087-h264_high.mp4" class="media" src="https://ksr-video.imgix.net/projects/2693324/video-741087-h264_high.mp4" title="" width="100%" height="350" style="max-width: 600px;outline: none" allow="encrypted-media; picture-in-picture" frameborder="0" allowfullscreen="">
  #document
    <html>
      <head><meta name="viewport" content="width=device-width"><style id="holderjs-style" type="text/css"></style></head> 
      <body class=" __plain_text_READY__">
        <video controls="" autoplay="" name="media">
          <source src="https://ksr-video.imgix.net/projects/2693324/video-741087-h264_high.mp4" type="video/mp4">
        </video> 
      </body>
    </html>
  </iframe>
</p>
```

**Comment by jeffreytse** [comment]
Hi @honggaruy,

This issue has been addressed and fixed. Please update the plugin to the latest version and try again.

Thanks and regards

**Comment by honggaruy** [comment]
It worked !! 
I can customize `autoplay` attribute now. Thanks !!

**Comment by jeffreytse** [comment]
Hi @honggaruy ,

You're welcome! And If you like my works, welcome to take a consideration to be my [sponsor](https://github.com/sponsors/jeffreytse), your sponsorship will help me sustain my open-source projects and make my new ideas come true. Also, you will get a badge on your profile page, I will tweet your sponsorship and add you to my [Backers.md](https://github.com/jeffreytse/jeffreytse/blob/master/BACKERS.md) list. : )

Thanks and regards
