### ISSUE TITLE
How to config displaymath auto number?

### ISSUE THREAD

**Issue by hexsix** [jeffreytse/jekyll-spaceship#54]
I wanna auto number the displaymath. Can I do that?

**Comment by jeffreytse** [comment]
Hi @hexsix 

Do you mean automatically number all equations entered in display mode?

Thanks and regards

**Comment by hexsix** [comment]
@jeffreytse Yes, that's it

**Comment by jeffreytse** [comment]
Hi @hexsix 

The TeX input processing in MathJax can be configured to add equation numbers to displayed equations automatically. This functionality is turned off by default, but it is easy to configure. You can get the detail by this [document](http://docs.mathjax.org/en/latest/input/tex/eqnumbers.html).


For reaching out this functionality, you should add the related configuration for this plugin,  the following snippet in `_config.yml` is for you:

```yml
# Where things are
jekyll-spaceship:
  mathjax-processor:
    config:
      tex:
        tags: 'ams'
```

If you want to learn more about the configuration of this plugin, please see [here](https://github.com/jeffreytse/jekyll-spaceship#configuration).

Thanks and regards

**Comment by hexsix** [comment]
Thank you @jeffreytse 
It works.

**Comment by jeffreytse** [comment]
Hi, @hexsix

You're welcome. And welcome to star this project for further updates in the future. : )

Thanks and regards
