### ISSUE TITLE
Bug: When using {:target="_blank"} in the first link of the cell it is applied to <td>, not <a> as expexted

### ISSUE THREAD

**Issue by rafaelspecta** [jeffreytse/jekyll-spaceship#55]
**Markdown**

```
| Sample table | |
| --------------|----------------------------|
| Item 1        | [Google](https://google.com){:target="_blank"}  |
| ^^            | ^^ [Yahoo](https://yahoo.com){:target="_blank"}  |
```

Genarated HTML

```html
<table>
  <thead>
    <tr>
      <th>Sample table</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="2">Item 1
        <br>
      </td>
      <td target="_blank" rowspan="2">
        <a href="https://google.com">Google</a>
        <br>
        <a href="https://yahoo.com" target="_blank">Yahoo</a>
      </td>
    </tr>
    <tr>
    </tr>
  </tbody>
</table>
```

Check this in the code:
```html
<td target="_blank" rowspan="2">
```

If I remove `{:target="_blank"}` from the first link the `target="_blank"` disappears from `<td>`

<img width="202" alt="table" src="https://user-images.githubusercontent.com/3139109/120785093-2cac5f80-c503-11eb-8131-abc9210e2794.png">

**Comment by rafaelspecta** [comment]
Forgot to mention that I am using the latest version directly from git

**Comment by jeffreytse** [comment]
Hi @rafaelspecta 

Thanks for the reporting, I will try to settle down this issue as soon as possible. And welcome to star this project for further updates in the future.

Thanks and regards

**Comment by rafaelspecta** [comment]
Thanks @jeffreytse . Let me know if you need any help.

**Comment by jeffreytse** [comment]
Hi @rafaelspecta 

Thanks for your patience. This issue has been addressed and settled down, please update your plugin to the latest version.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @rafaelspecta 

Does this issue be settled down? If you have any questions, please don't hesitate to tell me.

Thanks and regards

**Comment by rafaelspecta** [comment]
@jeffreytse seems to be working perfectly. Awesome, thanks.
