### ISSUE TITLE
Replace `\0' in code block to exclusion 

### ISSUE THREAD

**Issue by hoonti06** [jeffreytse/jekyll-spaceship#56]
Hi, I have some problem to convert cpp code block

I want to convert code block as below

```cpp
Trie* find(const char* key) {
    if (*key == '\0') return this;
    int idx = *key - 'A';
    if (!next[idx]) return NULL;
    return next[idx]->find(key + 1);
}

void insert(const char* key) {
    if (*key == '\0') finish = true;
    else {
        int idx = *key - 'A';
        if (!next[idx])
            next[idx] = new Trie();
        next[idx]->insert(key + 1);
}
```

<br>

but, result is not I expected
![image](https://user-images.githubusercontent.com/17792043/121445865-451ded80-c9cd-11eb-9933-a7cd98aefb94.png)

**Comment by jeffreytse** [comment]
Hi @hoonti06 

Thanks for the reporting, I will fixed this issue as soon as possible. And welcome to star this project for further updates in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @hoonti06 

Firstly, thanks for your patience, and now this issue has been addressed and fixed. Please update your plugin to the latest version and try again.

Thanks and regards

**Comment by hoonti06** [comment]
It's perfect. Thank you!
![](https://user-images.githubusercontent.com/17792043/121623152-2ccfd080-caaa-11eb-9601-c1fcce29763c.png)
