### ISSUE TITLE
Colspan feature is not  working

### ISSUE THREAD

**Issue by vandre** [jeffreytse/jekyll-spaceship#6]
I tried a couple of different examples and I could not get the colspan feature to work. I know the plugin is installed correctly because both the multiline and rowspan features work.

Here is an example I tried:

```
| :    Easy Multiline   : |||
| :----- | :----- | :------ |
| Apple  | Banana | Orange  \
| Apple  | Banana | Orange  \
| Apple  | Banana | Orange
| Apple  | Banana | Orange  \
| Apple  | Banana | Orange  |
| Apple  | Banana | Orange  |
```

Which renders

![image](https://user-images.githubusercontent.com/7480750/82493456-9ea73780-9aad-11ea-96e7-65ec49c1df97.png)

**Comment by jeffreytse** [comment]
Hi @vandre 
Can you provide more information about this issue (e.g. os, env, plugins you used)
Here is the example that you can see all the table features and no any feature not working.

* [https://github.com/jeffreytse/jekyll-jeffreytse-blog](https://github.com/jeffreytse/jekyll-jeffreytse-blog)
* [https://jeffreytse.net/example/2017/12/15/table-example.html](https://jeffreytse.net/example/2017/12/15/table-example.html)

**Comment by vandre** [comment]
I upgraded from 0.5.3 to 0.5.4 (on Windows, Ruby Version 2.6, Jekyll 4.0.1) and I can confirm that colspan feature is now rendering properly. Thank you for the quick turnaround!

**Comment by jeffreytse** [comment]
Hi @vandre 
I hope you enjoy using this plugin. If you like this project, a little star for it is your way make a clear statement: My work is valued. I would appreciate your support! Thank you!
