### ISSUE TITLE
[Feature request] Spotify podcasts

### ISSUE THREAD

**Issue by CochinoChingon** [jeffreytse/jekyll-spaceship#61]
Currently there's no support for podcasts, share link/embed code follows the same naming convention, except for `episode` in place of `track` I copied the snippet for Spotify and replaced `track` with `episode` And entered `[Spotify](URL)` but I still have a missing element where I run `bundle exec jekyll serve`

If I leave the default `![](Spotify I'll)` I have an empty line.

**Comment by jeffreytse** [comment]
Hi @CochinoChingon 

Thanks for your reaching out, I will try to support this feature as soon as possible. : )

Thanks and Regards

**Comment by jeffreytse** [comment]
Hi @CochinoChingon 

Thanks for your patience, this [feature](https://github.com/jeffreytse/jekyll-spaceship#spotify-podcast-usage) has been supported. Please update your plugin to the latest version.

```yml
# Open Gemfile and check your plugin is at Github version
gem 'rack', git: 'https://github.com/jeffreytse/jekyll-spaceship'
```

Welcome to star this project to have further updates in the future.
Also, hope you have a good day! : )

Thanks and Regards
