### ISSUE TITLE
MathJax not rendering when theme is changed

### ISSUE THREAD

**Issue by KaranJayachandra** [jeffreytse/jekyll-spaceship#65]
Hi, Good day! Thanks for the work on this repo. I am trying to use the Spaceship with this theme: [Jekyll Theme Console](https://github.com/b2a3e8/jekyll-theme-console). You can see the result [here](https://www.karanjayachandra.com/antennas/2021/10/26/ml-array.html). MathJax however doesnt't seem to be rendering both locally and on GitHub pages. Could you please point me in the right direction on how to fix this? I am still new to using code and might have missed something obvious. Thanks for your help!

**Comment by jeffreytse** [comment]
Hi @KaranJayachandra 

Thanks for the issue, this issue is similar with #64.

Thanks and Regards

**Comment by KaranJayachandra** [comment]
Hi @jeffreytse Thank you very much for the quick response. This script code was added by the theme. I have changed the theme to remove this. I am not sure this is a Mathjax issue because even without this, the render isn't working. Please have a look [here](https://www.karanjayachandra.com/antennas/2021/10/26/ml-array.html).

**Comment by jeffreytse** [comment]
Hi @KaranJayachandra 

Thanks for your support, and I would like to help you settle down your issue. Could you change your remote theme in your `_config.yml` to [jekyll-theme-yat](https://github.com/jeffreytse/jekyll-theme-yat) and try again? After this let me know the result. : )

Thanks an Regards

**Comment by KaranJayachandra** [comment]
Hi @jeffreytse! Thanks for the comment and great work on this repo. This is exactly the issue, there seems to be some conflict with [this](https://github.com/KaranJayachandra/jekyll-theme-console) theme.

**Comment by jeffreytse** [comment]
@KaranJayachandra Exactly the conflict with that theme, I need much more time to dig this issue, please be patient.

**Comment by jeffreytse** [comment]
@KaranJayachandra Thanks for your patience, after my digging, I have found out the reason, your theme has a high-level security configuration to prevent loading script from cross-site by the [Content Security Policy (CSP)](https://github.com/KaranJayachandra/jekyll-theme-console/blob/6e7b2946f6bb479297adcc518fdd3dbe148ab23a/_layouts/default.html#L3) head meta, you can settle your issue by removing it.

**Comment by KaranJayachandra** [comment]
Hi @jeffreytse ! Thanks for taking the time to look at this. This has resolved the issue. Your assistance is much appreciated!

**Comment by jeffreytse** [comment]
@KaranJayachandra You're welcome, and welcome to star this project for further updates in the future. : )
