### ISSUE TITLE
feature request: use only processors turned on in _config

### ISSUE THREAD

**Issue by agryaznov** [jeffreytse/jekyll-spaceship#7]
Hi! Nice plugin, thanks a lot!

I'd like to use only the *table-processor* as I don't need others.  
Would be a nice feature to apply only processors selected in *_config.yml*

Thanks.

**Comment by jeffreytse** [comment]
Hi @agryaznov 

This feature is in progress. You can configure this plugin for flexibility.
I will release in future. Welcome to star this project and keep focusing for new features.

Thanks and appreciates.
